name: jewish_app
description: "Base Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  action_broadcast: ^3.0.2
  country_code_picker: ^3.0.0
  phone_numbers_parser: ^6.0.0
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  qr_flutter: ^4.1.0
  table_calendar: ^3.0.9
  get_it: ^7.7.0
  dartz: ^0.10.1
  package_info_plus: ^8.0.2
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.1
  logger: ^2.3.0
  permission_handler: ^11.3.1
  responsive_builder: ^0.7.0
  intl: ^0.20.2 #0.19.0
  intl_utils: ^2.8.4
  injectable: ^2.4.2
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  pull_to_refresh_flutter3: ^2.0.2
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  modal_bottom_sheet: ^3.0.0-pre
  google_fonts: ^6.2.0
  freezed_annotation: ^2.4.1
  logging: ^1.2.0
  sentry: ^7.17.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  clippy_flutter: ^2.0.0-nullsafety.1
  animated_text_kit: ^4.2.2
  another_flushbar: ^1.12.30
  visibility_detector: ^0.4.0+2
  mutex: ^3.1.0
  auto_size_text: ^3.0.0
  image_picker: ^1.0.7
  flutter_rating_bar: ^4.0.1
  scroll_date_picker: ^3.8.0
  file_picker: ^8.0.0+1
  expandable: ^5.0.1
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  dotted_border: ^2.1.0
  timelines: ^0.1.0
  bloc: ^8.1.4
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  html: ^0.15.4
  encrypt: ^5.0.3
  barcode_widget: ^2.0.4
  country_pickers: ^3.0.1
  photo_manager: ^3.6.4
  photo_manager_image_provider: ^2.2.0
  path: ^1.8.3
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  injectable_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  test: ^1.22.0
  mockito: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/env/dev.env
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/judaism/
    - assets/fonts/
    - assets/images/png/
  # fonts:
  #   - family: Taz
  #     fonts:
  #       - asset: assets/fonts/Taz-Regular.ttf
  #       - asset: assets/fonts/Taz-Bold.ttf
  #         weight: 700
    
    